# Generated by Django 6.1 on 2026-08-20 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('license_plate', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=155)),
                ('color', models.CharField(max_length=50)),
                ('chassis', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
