# Generated by Django 6.0.8 on 2026-08-28 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('IN_PROGRESS', 'Em andamento'), ('WAITING_PARTS', 'Aguardando peças'), ('WAITING_CLIENT', 'Aguardando cliente'), ('DONE', 'Concluída'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição do serviço solicitado', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observações internas', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Valor total do serviço', max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='clients.client')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='employees.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
