# Generated by Django 6.0.8 on 2026-10-05 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_is_active'),
        ('service_order', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do serviço', max_digits=10),
        ),
        migrations.CreateModel(
            name='ServiceOrderProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_order_items', to='products.product')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='service_order.serviceorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_order_items', to='services.service')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_order.serviceorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
