# Generated by Django 6.1 on 2026-08-20 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do produto', max_length=255)),
                ('reference_code', models.CharField(help_text='Referência do produto', max_length=50)),
                ('barcode', models.CharField(blank=True, help_text='Código de barras (EAN)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada ou aplicação', null=True)),
                ('supplier', models.CharField(help_text='Fornecedor do produto', max_length=50)),
                ('brand', models.CharField(help_text='Marca do produto', max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Preço de custo pago ao fornecedor', max_digits=10)),
                ('margin_percentage', models.DecimalField(decimal_places=2, help_text='Margem desejada em %', max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Preço de venda para o cliente', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Quantidade atual no estoque')),
                ('min_stock_quantity', models.IntegerField(default=5, help_text='Estoque mínimo para alerta de reposição')),
                ('location', models.CharField(blank=True, help_text='Localização física na oficina (ex: Corredor A, Prateleira 3)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Produto ativo para novas vendas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
