# Generated by Django 6.0.8 on 2026-10-06 16:06

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física (CPF)'), ('PJ', 'Pessoa Jurídica (CNPJ)')], default='PF', max_length=2, verbose_name='Tipo de Cliente')),
                ('name', models.CharField(max_length=155)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('document', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('responsible', models.CharField(blank=True, max_length=155, null=True, verbose_name='Responsável / Frotista')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
