# Generated by Django 6.1 on 2026-08-20 14:28

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(help_text='Formato: 76800000', max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 digitos.', regex='^\\d{8}$')])),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('complement', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física (CPF)'), ('PJ', 'Pessoa Jurídica (CNPJ)')], default='PF', max_length=2, verbose_name='Tipo de Cliente')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=18, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('responsible', models.CharField(blank=True, max_length=155, null=True, verbose_name='Responsável / Frotista')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
