# Generated by Django 6.0.8 on 2026-10-06 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(help_text='Formato: 76800000', max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 digitos.', regex='^\\d{8}$')])),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('complement', models.TextField(max_length=255)),
            ],
        ),
    ]
